export const GET_TABLEDATA_SUCCESS = 'GET_TABLEDATA_SUCCESS';
export const GET_TABLEDATA_ERROR = 'GET_TABLEDATA_ERROR';

export const UPDATE_TABLEDATA_SUCCESS = 'UPDATE_TABLEDATA_SUCCESS';
export const UPDATE_TABLEDATA_ERROR = 'UPDATE_PROFILE_ERROR';