export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_ERROR = "REGISTER_ERROR"

export const AUTHENTICATE_USER = 'AUTHENTICATE_USER'
export const AUTHENTICATE_FAILED = 'AUTHENTICATE_FAILED'

export const LOGOUT = "LOGOUT"